print("DISCLAIMER: This isn't real. If I am claimed to be sorry, chances are I'm not to some degree.\n")
guests = ["Mark Twain", "Max Planck", "Albert Einstein", "Charles Ponzi"]
print("The guests originally intended to come are:\n" + guests[0] + ", " + guests[1] + ", " + guests[2] + ", and " + guests[3] + ".")
print("\nBut unfortunately, " + guests[0] + " couldn't come, so in his place is someone else.")
del(guests[0])
guests.insert(0, "Rose Gnecco")
print("\nThe new invitees are " + guests[0] + ", " + guests[1] + ", " + guests[2] + ", and " + guests[3] + ".")
print("\nBut wait! I found a bigger table. Updated list of guests incoming shortly.\n")
guests.insert(0, "Aiden Pearce") 
guests.insert(2, "Dinky Winks")
guests.append("Robbie Rotten")
print("We've got:\n" + guests[0] + ", " + guests[1] + ", " + guests[2] + ", " + guests[3] + ", " + guests[4] + ", " + guests[5] + ", and " + guests[6] + ".")
print("\nUpdate! I can only invite 2 people to dinner.")
robbie = guests.pop()
print(robbie + ", you're out. Sorry!")
ponzi = guests.pop()
print(ponzi + ", you're out. Sorry!")
einstein = guests.pop()
print(einstein + ", you're out. Sorry!")
planck = guests.pop()
print(planck + ", you're out. Sorry!")
gnecco = guests.pop()
print(gnecco + ", you're out. Sorry!")
print(guests[0] + ", you're still invited!")
print(guests[1] + ", you're still invited!")
del(guests[1])
del(guests[0])
print(guests)